steps:

  - name: 'gcr.io/cloud-builders/gradle'
    args: ['clean', 'build', '-x', 'test']
    
  - name: 'gcr.io/cloud-builders/jib'
    entrypoint: 'jib'
    args: ['--image=gcr.io/itacademy-379505/m23its', '--image-tag=latest']


